services:
  - type: web
    name: smartskin
    env: python
    buildCommand: |
      chmod +x build.sh
      chmod +x diagnose.sh
      ./build.sh
    preDeployCommand: ./diagnose.sh
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_ENV
        value: production
      - key: DISABLE_ESLINT_PLUGIN
        value: "true"
      - key: ESLINT_NO_DEV_ERRORS
        value: "true"
      - key: CI
        value: "false" 