services:
  - type: web
    name: smartskin
    env: python
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y tesseract-ocr
      chmod +x build.sh
      chmod +x diagnose.sh
      chmod +x minimal-build.sh
      chmod +x force-build.sh
      # Try main build, but fall back to force-build if any of them fail
      (./build.sh || ./minimal-build.sh || ./force-build.sh)
      # Always run force-build.sh as a final safety check
      [ -f frontend/build/index.html ] || ./force-build.sh
      # Verify build files exist
      ls -la frontend/build/
      echo "Build process completed"
    preDeployCommand: ./diagnose.sh
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSIONl
        value: 3.9.0
      - key: NODE_ENV
        value: production
      - key: DISABLE_ESLINT_PLUGIN
        value: "true"
      - key: ESLINT_NO_DEV_ERRORS
        value: "true"
      - key: CI
        value: "false"